Commit init #1 task 10
AndrewsSkBaron/UnitTesting pull request #1
Opened 2022-01-28 16:56 UTC by AndrewsSkBaron

2022-01-30 21:53 UTC, KirKarpov requested changes

2022-01-30 21:53 UTC, KirKarpov commented on src/main/resources/andrew-cart.json
> -{"cartName":"andrew-cart","realItems":[{"weight":1560.0,"name":"Audi","price":32026.9}],"virtualItems":[{"sizeOnDisk":20000.0,"name":"Windows","price":11.0}],"total":38445.479999999996}
Initial cart object shouldn't be changed. Why do need to remove data from it?

2022-01-30 21:53 UTC, KirKarpov commented on src/test/java/MainTest.java
> -    }
If I am not mistaken it is also initial file. It shouldn't be changed

2022-01-30 21:53 UTC, KirKarpov commented on src/test/java/parser/JsonParserTest.java
> +    void readFromFile() throws IOException {
Could you please explain what do you test? As of now I see that you are create file with no data in it. Also why you are using the same name of the file that already created ?

2022-01-30 21:53 UTC, KirKarpov commented on src/test/java/parser/JsonParserTest.java
> +    void writeToFile() throws IOException {
Your test doesn't test read from file method

2022-01-30 21:53 UTC, KirKarpov commented on src/test/java/parser/JsonParserTest.java
> +    public void testThrowsException() throws NoSuchFileException {
For this test please add dataset with not less than 5 parameters

2022-01-30 21:53 UTC, KirKarpov commented on src/test/java/shop/CartTest.java
> +    void deleteRealItem() {
If you are removing element why are you checking price with removed element?

2022-01-30 21:53 UTC, KirKarpov commented on src/test/java/shop/CartTest.java
> +    void deleteVirtualItem() {
same there

2022-02-01 07:41 UTC, closed without merging

2022-02-01 10:07 UTC, AndrewsSkBaron commented
кукку

2022-02-01 10:12 UTC, AndrewsSkBaron commented
Duplicate of #2